/bin/bash: /home/pi/lightshow2022/bin/start_microweb: Permission denied
INFO:root:Connected to local relay
INFO:root:Connected to local relay
INFO:root:[send_commands.py] - Sending i_off
INFO:root:Sent command to turn off speakers
/home/pi/lightshow2022/web/microweb/cgi-bin/web_controls.cgi:172: DeprecationWarning: cgi.escape is deprecated, use html.escape instead
  print("""<h2>Executed command: %s</h2>""" % cgi.escape(message))
INFO:root:Connected to local relay
INFO:root:Connected to local relay
INFO:root:Connected to local relay
INFO:root:[send_commands.py] - Sending i_off
INFO:root:Sent command to turn off system
/home/pi/lightshow2022/web/microweb/cgi-bin/web_controls.cgi:172: DeprecationWarning: cgi.escape is deprecated, use html.escape instead
  print("""<h2>Executed command: %s</h2>""" % cgi.escape(message))
INFO:root:Connected to local relay
INFO:root:Connected to local relay
INFO:root:Turned on lights
/home/pi/lightshow2022/web/microweb/cgi-bin/web_controls.cgi:172: DeprecationWarning: cgi.escape is deprecated, use html.escape instead
  print("""<h2>Executed command: %s</h2>""" % cgi.escape(message))
INFO:root:Connected to local relay
INFO:root:[send_commands.py] - Sending i_on
INFO:root:Sent command to turn on speakers
/home/pi/lightshow2022/web/microweb/cgi-bin/web_controls.cgi:172: DeprecationWarning: cgi.escape is deprecated, use html.escape instead
  print("""<h2>Executed command: %s</h2>""" % cgi.escape(message))
INFO:root:Connected to local relay
INFO:root:[send_commands.py] - Sending i_on
INFO:root:Sent command to turn on speakers
/home/pi/lightshow2022/web/microweb/cgi-bin/web_controls.cgi:172: DeprecationWarning: cgi.escape is deprecated, use html.escape instead
  print("""<h2>Executed command: %s</h2>""" % cgi.escape(message))
INFO:root:Connected to local relay
INFO:root:[send_commands.py] - Sending i_on
INFO:root:Sent command to turn on speakers (part of Start)
/home/pi/lightshow2022/web/microweb/cgi-bin/web_controls.cgi:172: DeprecationWarning: cgi.escape is deprecated, use html.escape instead
  print("""<h2>Executed command: %s</h2>""" % cgi.escape(message))
INFO:root:Connected to local relay
INFO:root:[send_commands.py] - Sending i_on
INFO:root:Sent command to turn on speakers (part of Start)
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
/home/pi/lightshow2022/web/microweb/cgi-bin/web_controls.cgi:172: DeprecationWarning: cgi.escape is deprecated, use html.escape instead
  print("""<h2>Executed command: %s</h2>""" % cgi.escape(message))
INFO:root:Connected to local relay
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
INFO:root:Turned off lights
/home/pi/lightshow2022/web/microweb/cgi-bin/web_controls.cgi:172: DeprecationWarning: cgi.escape is deprecated, use html.escape instead
  print("""<h2>Executed command: %s</h2>""" % cgi.escape(message))
INFO:root:Connected to local relay
INFO:root:[send_commands.py] - Sending i_off
INFO:root:Sent command to turn off system
/home/pi/lightshow2022/web/microweb/cgi-bin/web_controls.cgi:172: DeprecationWarning: cgi.escape is deprecated, use html.escape instead
  print("""<h2>Executed command: %s</h2>""" % cgi.escape(message))
INFO:root:Connected to local relay
INFO:root:[send_commands.py] - Sending i_off
INFO:root:Sent command to turn off speakers
/home/pi/lightshow2022/web/microweb/cgi-bin/web_controls.cgi:172: DeprecationWarning: cgi.escape is deprecated, use html.escape instead
  print("""<h2>Executed command: %s</h2>""" % cgi.escape(message))
INFO:root:Connected to local relay
INFO:root:[send_commands.py] - Sending i_off
INFO:root:Sent command to turn off system
/home/pi/lightshow2022/web/microweb/cgi-bin/web_controls.cgi:172: DeprecationWarning: cgi.escape is deprecated, use html.escape instead
  print("""<h2>Executed command: %s</h2>""" % cgi.escape(message))
INFO:root:Connected to local relay
INFO:root:[send_commands.py] - Sending i_on
INFO:root:Sent command to turn on speakers (part of Start)
/home/pi/lightshow2022/web/microweb/cgi-bin/web_controls.cgi:172: DeprecationWarning: cgi.escape is deprecated, use html.escape instead
  print("""<h2>Executed command: %s</h2>""" % cgi.escape(message))
INFO:root:Connected to local relay
INFO:root:Connected to local relay
INFO:root:Connected to local relay
INFO:root:Connected to local relay
INFO:root:Connected to local relay
INFO:root:Connected to local relay
Exception ignored in: <module 'threading' from '/usr/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 1263, in _shutdown
    def _shutdown():
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 195, in <lambda>
    signal.signal(signal.SIGTERM, lambda x, y: sys.exit(0))
SystemExit: 0
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
INFO:root:Connected to local relay
INFO:root:Connected to local relay
INFO:root:Turned on lights
/home/pi/lightshow2022/web/microweb/cgi-bin/web_controls.cgi:172: DeprecationWarning: cgi.escape is deprecated, use html.escape instead
  print("""<h2>Executed command: %s</h2>""" % cgi.escape(message))
INFO:root:Connected to local relay
INFO:root:Turned off lights
/home/pi/lightshow2022/web/microweb/cgi-bin/web_controls.cgi:172: DeprecationWarning: cgi.escape is deprecated, use html.escape instead
  print("""<h2>Executed command: %s</h2>""" % cgi.escape(message))
INFO:root:Connected to local relay
INFO:root:Connected to local relay
INFO:root:[send_commands.py] - Sending i_on
INFO:root:Sent command to turn on speakers (part of Start)
/home/pi/lightshow2022/web/microweb/cgi-bin/web_controls.cgi:172: DeprecationWarning: cgi.escape is deprecated, use html.escape instead
  print("""<h2>Executed command: %s</h2>""" % cgi.escape(message))
INFO:root:Connected to local relay
INFO:root:Connected to local relay
INFO:root:Connected to local relay
INFO:root:Connected to local relay
INFO:root:Connected to local relay
INFO:root:Connected to local relay
INFO:root:Connected to local relay
INFO:root:Connected to local relay
INFO:root:Connected to local relay
INFO:root:Connected to local relay
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
INFO:root:Connected to local relay
INFO:root:Connected to local relay
INFO:root:Connected to local relay
INFO:root:Connected to local relay
INFO:root:Connected to local relay
INFO:root:[send_commands.py] - Sending i_on
INFO:root:Sent command to turn on speakers (part of Start)
INFO:root:Connected to local relay
INFO:root:Connected to local relay
INFO:root:Connected to local relay
INFO:root:[send_commands.py] - Sending i_on
INFO:root:Sent command to turn on speakers
INFO:root:[send_commands.py] - Sending i_off
INFO:root:Sent command to turn off system
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
INFO:root:[send_commands.py] - Sending i_on
INFO:root:Sent command to turn on speakers
INFO:root:[send_commands.py] - Sending i_on
INFO:root:Sent command to turn on speakers
  File "/home/pi/lightshow2022/web/microweb/cgi-bin/web_controls.cgi", line 193
    log = f"{os.environ['SYNCHRONIZED_LIGHTS_HOME']/logs/microweb.log"
         ^
SyntaxError: f-string: expecting '}'
  File "/home/pi/lightshow2022/web/microweb/cgi-bin/web_controls.cgi", line 193
    log = f"{os.environ['SYNCHRONIZED_LIGHTS_HOME']/logs/microweb.log"
         ^
SyntaxError: f-string: expecting '}'
Traceback (most recent call last):
  File "/home/pi/lightshow2022/web/microweb/cgi-bin/web_controls.cgi", line 35, in <module>
    logger.setFormatter(formatter)
AttributeError: 'Logger' object has no attribute 'setFormatter'
Traceback (most recent call last):
  File "/home/pi/lightshow2022/web/microweb/cgi-bin/web_controls.cgi", line 35, in <module>
    logger.setFormatter(formatter)
AttributeError: 'Logger' object has no attribute 'setFormatter'
INFO:root:[send_commands.py] - Sending i_on
2022-12-14 00:19:07,579 - root - INFO - Sent command to turn on speakers
INFO:root:Sent command to turn on speakers
INFO:root:[send_commands.py] - Sending i_on
2022-12-14 00:24:41 - root - INFO - Sent command to turn on speakers
INFO:root:Sent command to turn on speakers
2022-12-14 00:25:31 - root - INFO - Connected to local relay server
INFO:root:Connected to local relay server
INFO:root:[send_commands.py] - Sending i_on
2022-12-14 00:25:31 - root - INFO - Sent command to turn on speakers
INFO:root:Sent command to turn on speakers
2022-12-14 00:25:38 - root - INFO - Connected to local relay server
INFO:root:Connected to local relay server
INFO:root:[send_commands.py] - Sending i_on
2022-12-14 00:25:38 - root - INFO - Sent command to turn on speakers
INFO:root:Sent command to turn on speakers
INFO:root:Starting relay...
INFO:root:Connected to Broadlink using LAN
127.0.0.1 - - [14/Dec/2022 00:31:04] "GET /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2022 00:31:12] "POST /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
INFO:root.relay:Got message
INFO:root.relay:('127.0.0.1', 56434) has connected
2022-12-14 00:31:13 - root - INFO - Connected to local relay server
INFO:root:Connected to local relay server
INFO:root:[send_commands.py] - Sending i_on
INFO:root.relay:b'i_on|'
2022-12-14 00:31:13 - root - INFO - Sent command to turn on speakers
INFO:root:Sent command to turn on speakers
INFO:root.relay:('127.0.0.1', 56434) has disconnected
2022-12-14 00:31:17 - root - INFO - Connected to local relay server
127.0.0.1 - - [14/Dec/2022 00:31:16] "POST /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
INFO:root.relay:Got message
INFO:root:Connected to local relay server
INFO:root:[send_commands.py] - Sending i_off
INFO:root.relay:('127.0.0.1', 56442) has connected
2022-12-14 00:31:17 - root - INFO - Sent command to turn off speakers
INFO:root:Sent command to turn off speakers
INFO:root.relay:b'i_off|'
INFO:root.relay:('127.0.0.1', 56442) has disconnected
sh: 1: stop_microweb: not found
sh: 1: stop_microweb: not found
INFO:root:Starting relay...
INFO:root:Connected to Broadlink using LAN
  File "/home/pi/lightshow2022/web/microweb/cgi-bin/web_controls.cgi", line 162
    command = f'{stop} && sleep 2 && {start} >> $SYNCHRONIZED_LIGHTS_HOME/logs/microweb.log 2>&1 &')
                                                                                                   ^
SyntaxError: invalid syntax
  File "/home/pi/lightshow2022/web/microweb/cgi-bin/web_controls.cgi", line 162
    command = f'{stop} && sleep 2 && {start} >> $SYNCHRONIZED_LIGHTS_HOME/logs/microweb.log 2>&1 &')
                                                                                                   ^
SyntaxError: invalid syntax
INFO:root:Starting relay...
INFO:root:Connected to Broadlink using LAN
INFO:root:Starting relay...
INFO:root:Connected to Broadlink using LAN
INFO:root:Starting relay...
INFO:root:Connected to Broadlink using LAN
  File "<fstring>", line 1
    (HOME])
         ^
SyntaxError: invalid syntax
  File "<fstring>", line 1
    (HOME])
         ^
SyntaxError: invalid syntax
INFO:root:Starting relay...
INFO:root:Connected to Broadlink using LAN
INFO:root:Starting relay...
INFO:root:Connected to Broadlink using LAN
INFO:root:Starting relay...
INFO:root:Connected to Broadlink using LAN
INFO:root:Starting relay...
INFO:root:Connected to Broadlink using LAN
2022-12-14 01:38:03 - root - INFO - Turned off lights
INFO:root:Turned off lights
192.168.187.135 - - [14/Dec/2022 01:37:49] "GET / HTTP/1.1" 200 -
192.168.187.135 - - [14/Dec/2022 01:37:49] "GET /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
192.168.187.135 - - [14/Dec/2022 01:37:50] "GET /favicon.png HTTP/1.1" 200 -
192.168.187.135 - - [14/Dec/2022 01:37:50] "GET /css/style.css HTTP/1.1" 200 -
192.168.187.135 - - [14/Dec/2022 01:37:50] "GET /favicon.png HTTP/1.1" 200 -
192.168.187.135 - - [14/Dec/2022 01:37:52] "POST /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
192.168.187.135 - - [14/Dec/2022 01:38:03] "POST /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
INFO:root.relay:Got message
2022-12-14 01:38:04 - root - INFO - Connected to local relay server
INFO:root:Connected to local relay server
INFO:root.relay:('127.0.0.1', 34528) has connected
INFO:root:[send_commands.py] - Sending i_off
INFO:root.relay:b'i_off|'
2022-12-14 01:38:04 - root - INFO - Sent command to turn off speakers
INFO:root:Sent command to turn off speakers
INFO:root.relay:('127.0.0.1', 34528) has disconnected
2022-12-14 01:38:06 - root - INFO - Connected to local relay server
192.168.187.135 - - [14/Dec/2022 01:38:05] "POST /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
INFO:root.relay:Got message
INFO:root:Connected to local relay server
INFO:root:[send_commands.py] - Sending i_off
2022-12-14 01:38:06 - root - INFO - Sent command to turn off speakers
INFO:root.relay:('127.0.0.1', 34532) has connected
INFO:root:Sent command to turn off speakers
INFO:root.relay:b'i_off|'
INFO:root.relay:('127.0.0.1', 34532) has disconnected
2022-12-14 01:38:11 - root - INFO - Connected to local relay server
192.168.187.135 - - [14/Dec/2022 01:38:10] "POST /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
INFO:root.relay:Got message
INFO:root:Connected to local relay server
INFO:root:[send_commands.py] - Sending i_on
2022-12-14 01:38:11 - root - INFO - Sent command to turn on speakers
INFO:root:Sent command to turn on speakers
INFO:root.relay:('127.0.0.1', 34536) has connected
INFO:root.relay:b'i_on|'
INFO:root.relay:('127.0.0.1', 34536) has disconnected
192.168.187.135 - - [14/Dec/2022 01:38:14] "POST /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
INFO:root.relay:Got message
2022-12-14 01:38:15 - root - INFO - Connected to local relay server
INFO:root:Connected to local relay server
INFO:root:[send_commands.py] - Sending i_off
2022-12-14 01:38:15 - root - INFO - Sent command to turn off speakers
INFO:root:Sent command to turn off speakers
INFO:root.relay:('127.0.0.1', 34540) has connected
INFO:root.relay:b'i_off|'
INFO:root.relay:('127.0.0.1', 34540) has disconnected
INFO:root:Starting relay...
INFO:root:Connected to Broadlink using LAN
  File "/home/pi/lightshow2022/web/microweb/cgi-bin/web_controls.cgi", line 174
    else:
       ^
SyntaxError: invalid syntax
sleep: invalid time interval ‘&&’
sleep: invalid time interval ‘/home/pi/lightshow2022/bin/stop_microweb’
sleep: invalid time interval ‘&&’
sleep: invalid time interval ‘sleep’
sleep: invalid time interval ‘&&’
sleep: invalid time interval ‘/home/pi/lightshow2022/bin/start_microweb’
sleep: invalid time interval ‘>>’
sleep: invalid time interval ‘$SYNCHRONIZED_LIGHTS_HOME/logs/microweb.log’
sleep: invalid time interval ‘2>&1’
Try 'sleep --help' for more information.
2022-12-14 18:54:58 - root - INFO - Connected to local relay server
INFO:root:Connected to local relay server
INFO:root:[send_commands.py] - Sending i_on
2022-12-14 18:54:58 - root - INFO - Sent command to turn on speakers (part of Start)
INFO:root:Sent command to turn on speakers (part of Start)
192.168.187.56 - - [14/Dec/2022 02:11:04] "GET / HTTP/1.1" 200 -
192.168.187.56 - - [14/Dec/2022 02:11:05] "GET /favicon.png HTTP/1.1" 200 -
192.168.187.56 - - [14/Dec/2022 02:11:05] "GET /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
192.168.187.56 - - [14/Dec/2022 02:11:05] CGI script exit status 0x100
192.168.187.56 - - [14/Dec/2022 02:11:05] "GET /favicon.ico HTTP/1.1" 200 -
192.168.187.56 - - [14/Dec/2022 02:11:43] "GET /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
192.168.187.56 - - [14/Dec/2022 02:11:44] "GET /css/style.css HTTP/1.1" 200 -
192.168.187.56 - - [14/Dec/2022 02:11:47] "POST /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
192.168.187.56 - - [14/Dec/2022 02:11:48] CGI script exit status 0x100
192.168.187.56 - - [14/Dec/2022 02:12:11] "GET /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
192.168.187.56 - - [14/Dec/2022 02:12:15] "POST /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
192.168.187.56 - - [14/Dec/2022 02:12:32] "GET /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
192.168.187.56 - - [14/Dec/2022 02:13:22] "POST /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
192.168.187.56 - - [14/Dec/2022 02:13:23] "POST /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
192.168.187.56 - - [14/Dec/2022 02:14:18] "POST /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
192.168.187.56 - - [14/Dec/2022 02:14:24] "GET /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
192.168.187.56 - - [14/Dec/2022 02:14:50] "POST /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
192.168.187.56 - - [14/Dec/2022 02:14:52] "GET /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
192.168.187.56 - - [14/Dec/2022 02:16:53] "POST /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
192.168.187.56 - - [14/Dec/2022 02:16:56] "POST /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
192.168.187.56 - - [14/Dec/2022 02:17:00] "GET /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
192.168.187.135 - - [14/Dec/2022 08:26:04] "GET / HTTP/1.1" 304 -
192.168.187.135 - - [14/Dec/2022 08:26:04] "GET /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
192.168.187.135 - - [14/Dec/2022 08:26:05] "GET /css/style.css HTTP/1.1" 304 -
127.0.0.1 - - [14/Dec/2022 08:48:34] code 501, message Unsupported method ('OPTIONS')
127.0.0.1 - - [14/Dec/2022 08:48:34] "OPTIONS /PiShare/Downloads/external/tor HTTP/1.1" 501 -
127.0.0.1 - - [14/Dec/2022 09:08:00] "GET /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2022 09:08:01] "GET /css/style.css HTTP/1.1" 304 -
127.0.0.1 - - [14/Dec/2022 09:08:02] "GET /favicon.png HTTP/1.1" 304 -
127.0.0.1 - - [14/Dec/2022 09:10:26] code 501, message Unsupported method ('OPTIONS')
127.0.0.1 - - [14/Dec/2022 09:10:26] "OPTIONS /PiShare HTTP/1.1" 501 -
127.0.0.1 - - [14/Dec/2022 09:38:28] code 501, message Unsupported method ('OPTIONS')
127.0.0.1 - - [14/Dec/2022 09:38:28] "OPTIONS /PiShare HTTP/1.1" 501 -
127.0.0.1 - - [14/Dec/2022 10:09:21] code 501, message Unsupported method ('OPTIONS')
127.0.0.1 - - [14/Dec/2022 10:09:21] "OPTIONS /PiShare HTTP/1.1" 501 -
127.0.0.1 - - [14/Dec/2022 12:59:48] code 501, message Unsupported method ('OPTIONS')
127.0.0.1 - - [14/Dec/2022 12:59:48] "OPTIONS /PiShare HTTP/1.1" 501 -
192.168.187.135 - - [14/Dec/2022 18:54:47] "GET / HTTP/1.1" 304 -
192.168.187.135 - - [14/Dec/2022 18:54:47] "GET /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
192.168.187.135 - - [14/Dec/2022 18:54:48] "GET /css/style.css HTTP/1.1" 304 -
192.168.187.135 - - [14/Dec/2022 18:54:57] "POST /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
INFO:root.relay:Got message
INFO:root.relay:('127.0.0.1', 38174) has connected
INFO:root.relay:b'i_on|'
INFO:root.relay:('127.0.0.1', 38174) has disconnected
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
2022-12-14 19:14:48 - root - INFO - Turned on lights
INFO:root:Turned on lights
2022-12-14 22:11:04 - root - INFO - Connected to local relay server
192.168.187.135 - - [14/Dec/2022 19:14:38] "POST /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.187.135', 51508)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/pi/lightshow2022/web/microweb/CGIHTTPServer_root.py", line 580, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/home/pi/lightshow2022/web/microweb/CGIHTTPServer_root.py", line 376, in handle
    self.handle_one_request()
  File "/home/pi/lightshow2022/web/microweb/CGIHTTPServer_root.py", line 344, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
127.0.0.1 - - [14/Dec/2022 20:58:38] "GET /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2022 20:58:39] "GET /css/style.css HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2022 21:36:48] code 501, message Unsupported method ('OPTIONS')
127.0.0.1 - - [14/Dec/2022 21:36:48] "OPTIONS /PiShare HTTP/1.1" 501 -
192.168.187.135 - - [14/Dec/2022 22:11:01] "GET /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
192.168.187.135 - - [14/Dec/2022 22:11:04] "POST /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
INFO:root.relay:Got message
INFO:root:Connected to local relay server
INFO:root:[send_commands.py] - Sending i_on
2022-12-14 22:11:04 - root - INFO - Sent command to turn on speakers (part of Start)
INFO:root:Sent command to turn on speakers (part of Start)
INFO:root.relay:('127.0.0.1', 38988) has connected
INFO:root.relay:b'i_on|'
INFO:root.relay:('127.0.0.1', 38988) has disconnected
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
2022-12-14 22:21:37 - root - INFO - Turned off lights
INFO:root:Turned off lights
192.168.187.135 - - [14/Dec/2022 22:21:29] "POST /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2022 22:22:03] code 501, message Unsupported method ('OPTIONS')
127.0.0.1 - - [14/Dec/2022 22:22:03] "OPTIONS / HTTP/1.1" 501 -
127.0.0.1 - - [14/Dec/2022 22:22:04] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2022 22:22:05] "GET /favicon.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2022 22:22:05] "GET /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2022 22:22:06] "GET /css/style.css HTTP/1.1" 200 -
192.168.187.135 - - [14/Dec/2022 22:25:12] "POST /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
INFO:root.relay:Got message
INFO:root.relay:('127.0.0.1', 39058) has connected
2022-12-14 22:25:13 - root - INFO - Connected to local relay server
INFO:root:Connected to local relay server
INFO:root:[send_commands.py] - Sending i_off
INFO:root.relay:b'i_off|'
2022-12-14 22:25:13 - root - INFO - Sent command to turn off system
INFO:root:Sent command to turn off system
INFO:root.relay:b'Sent command: i_off'
INFO:root:Starting relay...
INFO:root:Connected to Broadlink using LAN
2022-12-15 22:32:44 - root - INFO - Connected to local relay server
INFO:root:Connected to local relay server
INFO:root:[send_commands.py] - Sending i_on
2022-12-15 22:32:44 - root - INFO - Sent command to turn on speakers (part of Start)
INFO:root:Sent command to turn on speakers (part of Start)
192.168.187.135 - - [15/Dec/2022 22:32:40] "GET / HTTP/1.1" 304 -
192.168.187.135 - - [15/Dec/2022 22:32:40] "GET /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
192.168.187.135 - - [15/Dec/2022 22:32:41] "GET /css/style.css HTTP/1.1" 304 -
192.168.187.135 - - [15/Dec/2022 22:32:43] "POST /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
INFO:root.relay:Got message
INFO:root.relay:('127.0.0.1', 47384) has connected
INFO:root.relay:b'i_on|'
INFO:root.relay:('127.0.0.1', 47384) has disconnected
2022-12-15 22:32:49 - root - INFO - Connected to local relay server
INFO:root:Connected to local relay server
192.168.187.135 - - [15/Dec/2022 22:32:48] "POST /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
INFO:root.relay:Got message
INFO:root:[send_commands.py] - Sending i_on
2022-12-15 22:32:49 - root - INFO - Sent command to turn on speakers
INFO:root:Sent command to turn on speakers
INFO:root.relay:('127.0.0.1', 47388) has connected
INFO:root.relay:b'i_on|'
INFO:root.relay:('127.0.0.1', 47388) has disconnected
Traceback (most recent call last):
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 1058, in <module>
    lightshow.audio_in()
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 511, in audio_in
    if audio_max2 < 7000 and "FREQ_BINS" in hc:
TypeError: argument of type 'Hardware' is not iterable
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 1058, in <module>
    lightshow.audio_in()
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 511, in audio_in
    if audio_max2 < 7000 and "FREQ_BINS" in hc:
TypeError: argument of type 'Hardware' is not iterable
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 1058, in <module>
    lightshow.audio_in()
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 511, in audio_in
    if audio_max2 < 7000 and "FREQ_BINS" in hc:
TypeError: argument of type 'Hardware' is not iterable
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 1058, in <module>
    lightshow.audio_in()
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 511, in audio_in
    if audio_max2 < 7000 and "FREQ_BINS" in hc:
TypeError: argument of type 'Hardware' is not iterable
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 1058, in <module>
    lightshow.audio_in()
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 511, in audio_in
    if audio_max2 < 7000 and "FREQ_BINS" in hc:
TypeError: argument of type 'Hardware' is not iterable
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 1058, in <module>
    lightshow.audio_in()
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 511, in audio_in
    if audio_max2 < 7000 and "FREQ_BINS" in hc:
TypeError: argument of type 'Hardware' is not iterable
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 1058, in <module>
    lightshow.audio_in()
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 511, in audio_in
    if audio_max2 < 7000 and "FREQ_BINS" in hc:
TypeError: argument of type 'Hardware' is not iterable
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 1058, in <module>
    lightshow.audio_in()
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 511, in audio_in
    if audio_max2 < 7000 and "FREQ_BINS" in hc:
TypeError: argument of type 'Hardware' is not iterable
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 1058, in <module>
    lightshow.audio_in()
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 511, in audio_in
    if audio_max2 < 7000 and "FREQ_BINS" in hc:
TypeError: argument of type 'Hardware' is not iterable
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 1058, in <module>
    lightshow.audio_in()
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 511, in audio_in
    if audio_max2 < 7000 and "FREQ_BINS" in hc:
TypeError: argument of type 'Hardware' is not iterable
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 1058, in <module>
    lightshow.audio_in()
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 511, in audio_in
    if audio_max2 < 7000 and "FREQ_BINS" in hc:
TypeError: argument of type 'Hardware' is not iterable
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 1058, in <module>
    lightshow.audio_in()
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 511, in audio_in
    if audio_max2 < 7000 and "FREQ_BINS" in hc:
TypeError: argument of type 'Hardware' is not iterable
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 1058, in <module>
    lightshow.audio_in()
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 511, in audio_in
    if audio_max2 < 7000 and "FREQ_BINS" in hc:
TypeError: argument of type 'Hardware' is not iterable
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 1058, in <module>
    lightshow.audio_in()
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 511, in audio_in
    if audio_max2 < 7000 and "FREQ_BINS" in hc:
TypeError: argument of type 'Hardware' is not iterable
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 1058, in <module>
    lightshow.audio_in()
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 511, in audio_in
    if audio_max2 < 7000 and "FREQ_BINS" in hc:
TypeError: argument of type 'Hardware' is not iterable
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 1058, in <module>
    lightshow.audio_in()
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 511, in audio_in
    if audio_max2 < 7000 and "FREQ_BINS" in hc:
TypeError: argument of type 'Hardware' is not iterable
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 1058, in <module>
    lightshow.audio_in()
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 511, in audio_in
    if audio_max2 < 7000 and "FREQ_BINS" in hc:
TypeError: argument of type 'Hardware' is not iterable
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 1058, in <module>
    lightshow.audio_in()
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 511, in audio_in
    if audio_max2 < 7000 and "FREQ_BINS" in hc:
TypeError: argument of type 'Hardware' is not iterable
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 1058, in <module>
    lightshow.audio_in()
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 511, in audio_in
    if audio_max2 < 7000 and "FREQ_BINS" in hc:
TypeError: argument of type 'Hardware' is not iterable
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 1058, in <module>
    lightshow.audio_in()
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 511, in audio_in
    if audio_max2 < 7000 and "FREQ_BINS" in hc:
TypeError: argument of type 'Hardware' is not iterable
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 1058, in <module>
    lightshow.audio_in()
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 511, in audio_in
    if audio_max2 < 7000 and "FREQ_BINS" in hc:
TypeError: argument of type 'Hardware' is not iterable
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 1058, in <module>
    lightshow.audio_in()
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 511, in audio_in
    if audio_max2 < 7000 and "FREQ_BINS" in hc:
TypeError: argument of type 'Hardware' is not iterable
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 1058, in <module>
    lightshow.audio_in()
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 511, in audio_in
    if audio_max2 < 7000 and "FREQ_BINS" in hc:
TypeError: argument of type 'Hardware' is not iterable
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 1058, in <module>
    lightshow.audio_in()
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 511, in audio_in
    if audio_max2 < 7000 and "FREQ_BINS" in hc:
TypeError: argument of type 'Hardware' is not iterable
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 1058, in <module>
    lightshow.audio_in()
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 511, in audio_in
    if audio_max2 < 7000 and "FREQ_BINS" in hc:
TypeError: argument of type 'Hardware' is not iterable
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 1058, in <module>
    lightshow.audio_in()
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 511, in audio_in
    if audio_max2 < 7000 and "FREQ_BINS" in hc:
TypeError: argument of type 'Hardware' is not iterable
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 1058, in <module>
    lightshow.audio_in()
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 511, in audio_in
    if audio_max2 < 7000 and "FREQ_BINS" in hc:
TypeError: argument of type 'Hardware' is not iterable
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 1058, in <module>
    lightshow.audio_in()
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 511, in audio_in
    if audio_max2 < 7000 and "FREQ_BINS" in hc:
TypeError: argument of type 'Hardware' is not iterable
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 1058, in <module>
    lightshow.audio_in()
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 511, in audio_in
    if audio_max2 < 7000 and "FREQ_BINS" in hc:
TypeError: argument of type 'Hardware' is not iterable
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 1058, in <module>
    lightshow.audio_in()
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 511, in audio_in
    if audio_max2 < 7000 and hasattr(hc, "FREQ_BINS") :
TypeError: argument of type 'Hardware' is not iterable
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
2022-12-15 22:47:01 - root - INFO - Turned off lights
INFO:root:Turned off lights
2022-12-15 22:48:19 - root - INFO - Connected to local relay server
192.168.187.135 - - [15/Dec/2022 22:36:20] "POST /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
192.168.187.135 - - [15/Dec/2022 22:36:58] "POST /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.187.135', 60776)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/pi/lightshow2022/web/microweb/CGIHTTPServer_root.py", line 580, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/home/pi/lightshow2022/web/microweb/CGIHTTPServer_root.py", line 376, in handle
    self.handle_one_request()
  File "/home/pi/lightshow2022/web/microweb/CGIHTTPServer_root.py", line 344, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
192.168.187.135 - - [15/Dec/2022 22:39:55] "POST /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.187.135', 60800)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/pi/lightshow2022/web/microweb/CGIHTTPServer_root.py", line 580, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/home/pi/lightshow2022/web/microweb/CGIHTTPServer_root.py", line 376, in handle
    self.handle_one_request()
  File "/home/pi/lightshow2022/web/microweb/CGIHTTPServer_root.py", line 344, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
192.168.187.135 - - [15/Dec/2022 22:45:18] "POST /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
192.168.187.135 - - [15/Dec/2022 22:46:53] "POST /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
192.168.187.135 - - [15/Dec/2022 22:48:18] "POST /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
INFO:root.relay:Got message
INFO:root:Connected to local relay server
INFO:root:[send_commands.py] - Sending i_on
INFO:root.relay:('127.0.0.1', 47556) has connected
2022-12-15 22:48:19 - root - INFO - Sent command to turn on speakers (part of Start)
INFO:root:Sent command to turn on speakers (part of Start)
INFO:root.relay:b'i_on|'
INFO:root.relay:('127.0.0.1', 47556) has disconnected
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
2022-12-15 23:07:17 - root - INFO - Turned off lights
INFO:root:Turned off lights
INFO:root:Starting relay...
INFO:root:Connected to Broadlink using LAN
2022-12-16 22:30:21 - root - INFO - Connected to local relay server
INFO:root:Connected to local relay server
INFO:root:[send_commands.py] - Sending i_on
2022-12-16 22:30:21 - root - INFO - Sent command to turn on speakers (part of Start)
INFO:root:Sent command to turn on speakers (part of Start)
192.168.187.135 - - [16/Dec/2022 22:30:18] "GET / HTTP/1.1" 304 -
192.168.187.135 - - [16/Dec/2022 22:30:18] "GET /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
192.168.187.135 - - [16/Dec/2022 22:30:19] "GET /css/style.css HTTP/1.1" 304 -
192.168.187.135 - - [16/Dec/2022 22:30:20] "POST /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
INFO:root.relay:Got message
INFO:root.relay:('127.0.0.1', 55060) has connected
INFO:root.relay:b'i_on|'
INFO:root.relay:('127.0.0.1', 55060) has disconnected
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
INFO:root:Starting relay...
INFO:root:Connected to Broadlink using LAN
2022-12-17 00:47:10 - root - INFO - Turned off lights
INFO:root:Turned off lights
2022-12-17 09:26:41 - root - INFO - Connected to local relay server
192.168.187.135 - - [17/Dec/2022 00:47:03] "POST /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
192.168.187.135 - - [17/Dec/2022 09:26:35] "GET / HTTP/1.1" 304 -
192.168.187.135 - - [17/Dec/2022 09:26:35] "GET /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
192.168.187.135 - - [17/Dec/2022 09:26:36] "GET /favicon.png HTTP/1.1" 304 -
192.168.187.135 - - [17/Dec/2022 09:26:36] "GET / HTTP/1.1" 304 -
192.168.187.135 - - [17/Dec/2022 09:26:36] "GET /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
192.168.187.135 - - [17/Dec/2022 09:26:40] "POST /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
INFO:root.relay:Got message
INFO:root:Connected to local relay server
INFO:root:[send_commands.py] - Sending i_on
2022-12-17 09:26:41 - root - INFO - Sent command to turn on speakers (part of Start)
INFO:root:Sent command to turn on speakers (part of Start)
INFO:root.relay:('127.0.0.1', 45490) has connected
INFO:root.relay:b'i_on|'
INFO:root.relay:('127.0.0.1', 45490) has disconnected
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
2022-12-17 17:23:33 - root - INFO - Turned off lights
INFO:root:Turned off lights
2022-12-17 17:23:39 - root - INFO - Turned on lights
INFO:root:Turned on lights
2022-12-17 17:23:46 - root - INFO - Turned on lights
INFO:root:Turned on lights
INFO:root:Starting relay...
INFO:root:Connected to Broadlink using LAN
2022-12-18 12:42:07 - root - INFO - Connected to local relay server
INFO:root:Connected to local relay server
192.168.187.135 - - [18/Dec/2022 12:42:03] "GET / HTTP/1.1" 304 -
192.168.187.135 - - [18/Dec/2022 12:42:04] "GET /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
192.168.187.135 - - [18/Dec/2022 12:42:05] "GET /css/style.css HTTP/1.1" 304 -
192.168.187.135 - - [18/Dec/2022 12:42:06] "POST /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
INFO:root.relay:Got message
INFO:root:[send_commands.py] - Sending i_on
2022-12-18 12:42:07 - root - INFO - Sent command to turn on speakers (part of Start)
INFO:root:Sent command to turn on speakers (part of Start)
INFO:root.relay:('127.0.0.1', 39572) has connected
INFO:root.relay:b'i_on|'
INFO:root.relay:('127.0.0.1', 39572) has disconnected
INFO:root:Starting relay...
INFO:root:Connected to Broadlink using LAN
2022-12-19 07:38:49 - root - INFO - Turned on lights
INFO:root:Turned on lights
192.168.187.56 - - [19/Dec/2022 06:31:16] "POST /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
192.168.187.56 - - [19/Dec/2022 07:38:42] "POST /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
127.0.0.1 - - [19/Dec/2022 08:05:08] "GET / HTTP/1.1" 304 -
127.0.0.1 - - [19/Dec/2022 08:05:08] "GET /favicon.png HTTP/1.1" 200 -
127.0.0.1 - - [19/Dec/2022 08:05:08] "GET /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
127.0.0.1 - - [19/Dec/2022 08:05:09] "GET /css/style.css HTTP/1.1" 200 -
192.168.187.135 - - [19/Dec/2022 22:24:19] "GET / HTTP/1.1" 304 -
192.168.187.135 - - [19/Dec/2022 22:24:19] "GET /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
192.168.187.135 - - [19/Dec/2022 22:24:20] "GET /css/style.css HTTP/1.1" 304 -
192.168.187.135 - - [19/Dec/2022 22:24:28] "POST /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
INFO:root.relay:Got message
2022-12-19 22:24:29 - root - INFO - Connected to local relay server
INFO:root:Connected to local relay server
INFO:root:[send_commands.py] - Sending i_on
2022-12-19 22:24:29 - root - INFO - Sent command to turn on speakers (part of Start)
INFO:root.relay:('127.0.0.1', 55426) has connected
INFO:root:Sent command to turn on speakers (part of Start)
INFO:root.relay:b'i_on|'
INFO:root.relay:('127.0.0.1', 55426) has disconnected
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
2022-12-19 22:25:05 - root - INFO - Turned on lights
INFO:root:Turned on lights
INFO:root:Starting relay...
INFO:root:Connected to Broadlink using LAN
2022-12-20 16:59:38 - root - INFO - Connected to local relay server
192.168.187.135 - - [20/Dec/2022 16:59:35] "GET /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
192.168.187.135 - - [20/Dec/2022 16:59:37] "POST /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
INFO:root.relay:Got message
INFO:root:Connected to local relay server
INFO:root:[send_commands.py] - Sending i_on
2022-12-20 16:59:38 - root - INFO - Sent command to turn on speakers (part of Start)
INFO:root:Sent command to turn on speakers (part of Start)
INFO:root.relay:('127.0.0.1', 43942) has connected
INFO:root.relay:b'i_on|'
INFO:root.relay:('127.0.0.1', 43942) has disconnected
Traceback (most recent call last):
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 1101, in <module>
    lightshow.audio_in()
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 537, in audio_in
    data = stream_reader()
  File "/home/pi/lightshow2022/py/synchronized_lights.py", line 444, in <lambda>
    stream_reader = lambda: self.streaming.read()[-1]
alsaaudio.ALSAAudioError: Input/output error [default:CARD=MIC]
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
INFO:root:Starting relay...
INFO:root:Connected to Broadlink using LAN
2022-12-20 18:12:36 - root - INFO - Connected to local relay server
192.168.187.135 - - [20/Dec/2022 18:12:33] "GET / HTTP/1.1" 304 -
192.168.187.135 - - [20/Dec/2022 18:12:33] "GET /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
192.168.187.135 - - [20/Dec/2022 18:12:35] "GET /css/style.css HTTP/1.1" 304 -
192.168.187.135 - - [20/Dec/2022 18:12:36] "POST /cgi-bin/web_controls.cgi HTTP/1.1" 200 -
INFO:root.relay:Got message
INFO:root:Connected to local relay server
INFO:root:[send_commands.py] - Sending i_on
2022-12-20 18:12:36 - root - INFO - Sent command to turn on speakers (part of Start)
INFO:root:Sent command to turn on speakers (part of Start)
INFO:root.relay:('127.0.0.1', 47442) has connected
INFO:root.relay:b'i_on|'
INFO:root.relay:('127.0.0.1', 47442) has disconnected
